const actions = {
    TOGGLE_DELETING: "TOGGLE_DELETING",
    TOGGLE_EDITING: "TOGGLE_EDITING",
    UPDATE_CARD_INDEX: "UPDATE_CARD_INDEX",
    DELETE_CARD_INDEX: "DELETE_CARD_INDEX",
    UPDATE_PRODUCTS_LIST: "UPDATE_PRODUCTS_LIST",
    ADD_PRODUCTS_LIST: "ADD_PRODUCTS_LIST",
    SEND_THUMB_AND_TITLE: "SEND_THUMB_AND_TITLE",
    CREATING_OR_EDITING: "CREATING_OR_EDITING",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    EDIT_PRODUCT: "EDIT_PRODUCT",
};

export default actions;