const actions = {
    TOGGLE_DELETING: "TOGGLE_DELETING",
    UPDATE_CARD_INDEX: "UPDATE_CARD_INDEX",
    DELETE_CARD_INDEX: "DELETE_CARD_INDEX",
    UPDATE_PRODUCTS_LIST: "UPDATE_PRODUCTS_LIST",
};

export default actions;