const actions = {
    TOGGLE_DELETING: "TOGGLE_DELETING",
    TOGGLE_EDITING: "TOGGLE_EDITING",
    UPDATE_CARD_INDEX: "UPDATE_CARD_INDEX",
    DELETE_CARD_INDEX: "DELETE_CARD_INDEX",
    UPDATE_PRODUCTS_LIST: "UPDATE_PRODUCTS_LIST",
    SEND_THUMB_AND_TITLE: "SEND_THUMB_AND_TITLE",
};

export default actions;